### PR TITLE
NVIDIA Device Plugin

### LINKED ISSUE #2538: Nvidia GPU support broken in master
Placeholder ticket for now, // TODO: investigation

Our E2E tests are showing us that building a cluster w/ `Standard_NC6` agent nodes are not able to schedule a pod for `nvidia-smi`.

@wbuchwalter FYI. If you're able to build from master and deploy a new cluster, it'd be awesome if you could try to repro!

### PR DESCRIPTION
**Pull request by sozercan**
**What this PR does / why we need it**:

As recommended by [Kubernetes GPU docs](https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/), device plugins are the path going forward for v1.8+ clusters.
Also, examples in ML tools such as [Kubeflow](https://github.com/kubeflow/kubeflow) are moving to use the `nvidia.com/gpu` resource (device plugin), which means that examples won't work out of the box on Azure. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

Adds support for NVIDIA Device Plugin for GPU agent pools by: 
* ~adding `DevicePlugin` feature gate for k8s versions >= 1.8 and <= 1.10~ (keeping accelerators feature gate for v1.6, v1.7, v1.8, v1.9)
* adding a daemonset for [nvidia-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) as `nvidia-device-plugin` add-on, which can be disabled
* installing [nvidia-docker2](https://github.com/NVIDIA/nvidia-docker) and [nvidia-docker-runtime](https://github.com/NVIDIA/nvidia-container-runtime)
* sets nvidia-docker-runtime as default docker runtime

**Special notes for your reviewer**:
~Pending approval from NVIDIA for `nvidia-docker2` and `nvidia-container-runtime`~
cc @lachie83 

~It is disabled for v1.10 for now since NVIDIA device plugin doesn't have an image yet~

fixes #2538

### CODE REVIEW

**Comment by jackfrancis** [comment]
@sozercan Does this effectively replace the existing nvidia/GPU implementation?

Thanks so much for this!

**Comment by sozercan** [comment]
@jackfrancis we still need the installation of gpu drivers, but this new implementation allows automatic discovery of gpu resources in pods (no need to mount driver explicitly).

also, replaces `accelerators` feature gate for v1.8 and v1.9 with `DevicePlugin` feature gate (no longer needed for v1.10+)

**Comment by jackfrancis** [comment]
Got it. Have you done any manual cluster deployment tests using an api model that resembles this one?

https://github.com/Azure/acs-engine/blob/master/examples/e2e-tests/kubernetes/gpu-enabled/definition.json

If so, and if things look good from your end, I'd like to run our GPU E2E tests, which build that cluster and then try to run an nvidia workload against it. Specifically:

https://github.com/Azure/acs-engine/blob/master/test/e2e/kubernetes/workloads/nvidia-smi.yaml

**Comment by sozercan** [comment]
@jackfrancis i modified the e2e tests for it: https://github.com/Azure/acs-engine/pull/2545/files#diff-3509723ee1508f842e543bf659b43e20R435

it should run for this automatically: https://github.com/sozercan/acs-engine/blob/d79c0d84438fbbe0ac6de8cf6ac1497479f2c97d/test/e2e/kubernetes/workloads/nvidia-smi-deviceplugin.yaml

**Comment by sozercan** [comment]
Tested manually on similar GPU enabled definitions. Please run e2e when you can, but don't merge if it passes please.

**Comment by jackfrancis** [comment]
@sozercan FYI rebased/force-pushed to get ready for master merge when we have the all clear

**Comment by sozercan** [comment]
@jackfrancis we have the approval from NVIDIA, ready for review finally!
Add-on is automatically enabled only for k8s == 1.10 with N Series (no image for 1.11 yet).

cc @lachie83 @wbuchwalter

**Comment by jackfrancis** [comment]
@sozercan Great news! Let's aim to get this in this week! (May need to dance the salsa with changes going into master, but I'll be your partner)

File: pkg/acsengine/defaults-kubelet.go [hunk 1]
```diff
@@ -97,17 +98,21 @@ func setKubeletConfig(cs *api.ContainerService) {
...
 			profile.KubernetesConfig = &api.KubernetesConfig{}
 			profile.KubernetesConfig.KubeletConfig = copyMap(profile.KubernetesConfig.KubeletConfig)
 		}
 		setMissingKubeletValues(profile.KubernetesConfig, o.KubernetesConfig.KubeletConfig)
-		if !common.IsKubernetesVersionGe(o.OrchestratorVersion, "1.11.0") {
-			addDefaultFeatureGates(profile.KubernetesConfig.KubeletConfig, o.OrchestratorVersion, "1.6.0", "Accelerators=true")
+
+		// For N Series (GPU) VMs
+		if strings.Contains(profile.VMSize, "Standard_N") {
+			if !cs.Properties.IsNVIDIADevicePluginEnabled() { // enabling accelerators for Kubernetes >= 1.6 to <= 1.9
```
Comment (jackfrancis) [inline pkg/acsengine/defaults-kubelet.go]: Is this comment true that this is not expected to engage for 1.10.0 and 1.11.0?

Comment (sozercan) [reply pkg/acsengine/defaults-kubelet.go]: that's right, we don't want `accelerators` flag for NVIDIA device plugin. 
Added a check for v1.11 also, just in case user has disabled `nvidia-device-plugin` explicitly so cluster should still be up but there will not be any GPUs available for K8s.
