### PR TITLE
fix(deploy): Change SP creation logging to debug

### LINKED ISSUE #1120: Don't display SP debug output in `acs-engine deploy`
`acs-engine deploy` displays logging related to service principal creation that is confusing for the user:

```
$ ./acs-engine deploy --dns-prefix party-monster --location westus --subscription-id ... --resource-group party-monster examples/kubernetes.json
WARN[0003] apimodel: missing masterProfile.dnsPrefix will use "party-monster"
WARN[0003] apimodel: ServicePrincipalProfile was missing or empty, creating application...
WARN[0005] created application with applicationID (c6735595-d1c3-41ed-a6f9-4b073ebee0ba) and servicePrincipalObjectID (4629af46-0700-47fc-9bc8-28b64662300d).
WARN[0005] apimodel: ServicePrincipalProfile was empty, assigning role to application...
WARN[0006] Failed to create role assignment (will retry): "authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"PrincipalNotFound\" Message=\"Principal 4629af46070047fc9bc828b64662300d does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\""
WARN[0009] Failed to create role assignment (will retry): "authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"PrincipalNotFound\" Message=\"Principal 4629af46070047fc9bc828b64662300d does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\""
WARN[0012] Failed to create role assignment (will retry): "authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"PrincipalNotFound\" Message=\"Principal 4629af46070047fc9bc828b64662300d does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\""
WARN[0016] Failed to create role assignment (will retry): "authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"PrincipalNotFound\" Message=\"Principal 4629af46070047fc9bc828b64662300d does not exist in the directory 72f988bf-86f1-41af-91ab-2d7cd011db47.\""
````

Long and short is that these messages are related to AAD synchronization and don't imply any problem. We should move this output to debug log level.

### PR DESCRIPTION
**Pull request by seanknox**
**What this PR does / why we need it**: Changes SP/AAD logging to debug, so not to scare users using `acs-engine deploy`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1120 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.io/reviews/azure/acs-engine/1121)

### CODE REVIEW

File: pkg/armhelpers/graph.go [hunk 1]
```diff
@@ -1,116 +1,116 @@
...
-			log.Warnf("Failed to create role assignment (will retry): %q", err)
-			time.Sleep(3 * time.Second)
-			continue
-		}
-		break
-	}
-
-	return nil
-}
+package armhelpers
```
Comment (anhowe) [inline pkg/armhelpers/graph.go]: why did this file change so much?

Comment (seanknox) [inline pkg/armhelpers/graph.go]: `gofmt`.
