### PR TITLE
Disable AKS VHD for sovereign clouds

### LINKED ISSUE #3873: Issue running v0.22.0 for Azure Gov
Hello,

I encountered an issue when I tried deploying an acs-engine cluster on Azure Gov cloud using v0.22.0; however, the issue does not exist in v0.21.2.

```shell
thfalgou@sandboxgov:~/git/acs-engine/examples/kubernetes-releases$ acs-engine deploy --subscription-id $SUB --dns-prefix thfalgou-gov  --location usgovtexas --api-model kubernetes1.10.json --debug --azure-env AzureUSGovernmentCloud
...
INFO[0031] Starting ARM Deployment (thfalgou-gov-1649987974). This will take some time...
INFO[0093] Finished ARM Deployment (thfalgou-gov-1649987974). Error: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"}]
FATA[0093] Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidParameter\",\r\n    \"target\": \"imageReference.publisher\",\r\n    \"message\": \"The value of parameter imageReference.publisher is invalid.\"\r\n  }\r\n}"}]
```

I then replaced acs-engine v0.22.0 with v0.21.2 and it worked without issue:
```
thfalgou@sandboxgov:~/git/acs-engine/examples/kubernetes-releases$ acs-engine deploy --subscription-id $SUB --dns-prefix thfalgou-gov  --location usgovtexas --api-model kubernetes1.10.json --debug --azure-env AzureUSGovernmentCloud
...
INFO[0018] Starting ARM Deployment (thfalgou-gov-1952617817). This will take some time...
INFO[0426] Finished ARM Deployment (thfalgou-gov-1952617817). Succeeded
```

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Temporarily set the AKS distro to Ubuntu as the image is not yet published in Sovereign Clouds and it causes deployments to fail in 0.22.0.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #3873 

**Special notes for your reviewer**:

**If applicable**:
- [ ] documentation
- [ ] unit tests
- [ ] tested backward compatibility (ie. deploy with previous version, upgrade with this branch)

**Release note**:

```release-note
```

### CODE REVIEW

File: pkg/acsengine/defaults.go [hunk 1]
```diff
@@ -158,6 +158,12 @@ var (
 			},
 			api.RHEL:   DefaultRHELOSImageConfig,
 			api.CoreOS: DefaultCoreOSImageConfig,
+			api.AKS: {
```
Comment (CecileRobertMichon) [inline pkg/acsengine/defaults.go]: the definition is copied from line 153
